### ISSUE TITLE
Hey, would you mind helping me ?

### ISSUE THREAD

**Issue by ascogo** [avysk/dumbstone#2]
Hello, i am a student and go player. I found your project very interesting and i think it might help me for my own school project but i am a real newbie in code (pretty bad).
I want to use Leela Zero to create a basic anticheat in order to prevent people from using leela online.
If you are interested in helping me that would be great!
I think that i just need to understand how your code works.
anyway, thank you for your time.

**Comment by avysk** [comment]
...and why exactly did you open the issue?
